---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "aws-ebs-pv"
  annotations:
    pv.beta.kubernetes.io/gid: "54321"
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: "aws://us-east-1a/vol-0deea9d2a79beb421"
    fsType: ext4
