--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    app: orclapp
  name: orcl-rc
spec: 
  replicas: 1
  selector: 
    app: orclapp
  template: 
    metadata: 
      labels: 
        app: orclapp
    spec: 
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
      containers: 
        - 
          env: 
            - 
              name: ORACLE_SID
              value: ORCLCDB
            - 
              name: ORACLE_PDB
              value: ORCLPDB1
            - 
              name: ORACLE_PWD
              value: oracle
          image: dvohra/oracle-db:12.2.0.1-ee
          name: orcl
          ports: 
            - 
              containerPort: 1521
            - 
              containerPort: 5500
          volumeMounts: 
            - 
              mountPath: /opt/oracle/oradata
              name: aws-volume
      volumes: 
        - 
          persistentVolumeClaim:
            claimName: aws-ebs-pvc
          name: aws-volume
      imagePullSecrets: 	
            - 
              name: private-registry-key
