--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: hello-world-app
  name: hello-world
spec: 
  ports: 
    - 
      name: http
      port: 80
  selector: 
    app: hello-world-app
  type: LoadBalancer
